# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaed951935cf8bf87f8dda13aea75ff9c6f6405dc1d60810d72ae3054a0f0099cd8053a32a41a2c3d644778502fe574edd52dc08c41b765a52844536b09e4586

test:
  secret_key_base: 3b1afece20134da24adc197bdde3b7959a22b0a142bf68ecbd08dc14329dfd7ace2f224d078f278e9b9f8b38dcbae4d8d6f07fca88090a12cdcc99ba238d6e2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
